company_update_categories = {
  "Board Meeting": [
    "Board Meeting",
    "Committee Meeting",
    "Outcome of Board Meeting"
  ], 
  "Company Update": [
    "General",
    "Acquisition",
    "Agreement",
    "Allotment of Equity Shares",
    "Allotment of Warrants",
    "Award of Order / Receipt of Order",
    "Buy back",
    "Change in Directorate",
    "Change in Registered Office",
    "Clarification",
    "Declaration of NAV",
    "Delisting",
    "FCCBs",
    "Joint Venture",
    "Open Offer",
    "Press Release / Media Release",
    "Sale of shares",
    "Strike",
    "Utilisation of Funds",
    "Clarification of News Item",
    "Debt Securities",
    "Credit Rating",
    "Change of Name",
    "Disclosure under Clause 35A of the Listing Agreement",
    "NAV Declaration",
    "Shareholding",
    "Analyst / Investor Meet",
    "Reg. 13(3) - Statement of Investor Complaints",
    "Reg. 7(3) – Compliance Certificate (RTA & Compliance Officer)",
    "Reg. 40 (10) - PCS Certificate for Transfer / Transmission / Transposition",
    "Reg. 32 (1), (3) - Statement of Deviation & Variation",
    "Appointment of Director",
    "Appointment of Chairman",
    "Appointment of Chairman and Managing Director",
    "Appointment of Managing Director",
    "Appointment of Chief Executive Officer (CEO)",
    "Appointment of Chief Financial Officer (CFO)",
    "Appointment of Managing Director & CEO",
    "Appointment of Company Secretary / Compliance Officer",
    "Change in Financial Year",
    "Change in Auditors",
    "Increase of Authorised Capital",
    "Voluntary Delisting",
    "Board Meeting Deferred",
    "Board Meeting Adjourned",
    "Board Meeting Postponed",
    "Board Meeting Cancelled",
    "Board Meeting Rescheduled",
    "Resignation of Director",
    "Resignation of Chairman",
    "Resignation of Chairman and Managing Director",
    "Resignation of Chief Executive Officer (CEO)",
    "Resignation of Chief Financial Officer (CFO)",
    "Resignation of Managing Director",
    "Resignation of Statutory Auditors",
    "Demise",
    "Monthly Business Updates",
    "Trading Plan under SEBI (PIT) Regulations, 2015",
    "Code of Conduct under SEBI (PIT) Regulations, 2015",
    "Amendments to Memorandum & Articles of Association",
    "Cancellation of Dividend",
    "Allotment of ESOP / ESPS",
    "Closure of Buy Back",
    "Investor Presentation",
    "Press release (Revised)",
    "Annulment / Re-issue of forfeited shares",
    "Cessation",
    "Change in Management",
    "Change in Management Control",
    "Disclosure of IDR Holding",
    "Diversification / Disinvestment",
    "Institutional Placement Programme",
    "Issue of Securities",
    "Meeting Updates",
    "Memorandum of Understanding / Agreements",
    "Monitoring Agency Report",
    "Offer for Sale",
    "Open Offer - Updates",
    "Post Buyback Public Announcement",
    "Post Offer Public Announcement",
    "Preferential Issue",
    "Public Announcement-Buyback of Shares",
    "Public Announcement-Delisting",
    "Public Announcement-Open Offer",
    "Newspaper Publication",
    "Qualified Institutional Placement",
    "Raising of Funds",
    "Restructuring",
    "Retirement",
    "Scheme of Arrangement",
    "Strikes / Lockouts / Disturbances",
    "Appointment of Interim Resolution Professional (IRP)",
    "Winding-up",
    "Change in Registered Office Address",
    "Change in Corporate Office Address",
    "Press Release / Media Release (Revised)",
    "Appointment of Statutory Auditor/s",
    "Earnings Call Transcript",
    "Resignation of Company Secretary / Compliance Officer",
    "Initiation of Corporate Insolvency Resolution Process (CIRP) by Corporate Applicant",
    "Initiation of Corporate Insolvency Resolution Process (CIRP) by Financial Creditors",
    "Admission of application by Tribunal",
    "Public Announcement",
    "List of Creditors",
    "Replacement of Interim Resolution Professional (IRP)",
    "Intimation of meeting of Committee of Creditors",
    "Outcome of meeting of Committee of Creditors",
    "Invitation of Resolution Plan",
    "Resolution Plans received by Resolution Professional",
    "Filing of Resolution plan with Tribunal",
    "Approval of Resolution plan by Tribunal",
    "Rejection of Resolution plan by Tribunal",
    "Updates - Corporate Insolvency Resolution Process (CIRP)",
    "Liquidation - Corporate Insolvency Resolution Process (CIRP)",
    "Declaration of Book Closure / Record Date",
    "Quarterly AUM Disclosure",
    "Monthly AUM Disclosure",
    "Annual Disclosure – Investor Complaints",
    "Revision of outcome",
    "Funds raising by issuance of Debt Securities by Large Entities",
    "Reg. 24(A)-Annual Secretarial Compliance",
    "Certificate under Reg. 74 (5) of SEBI (DP) Regulations, 2018",
    "Agreements, Contracts, Arrangements, MOU",
    "Amalgamation / Merger",
    "De-merger",
    "Incorporation",
    "Notice Of Shareholders Meetings - Annual General Meeting",
    "Notice Of Shareholders Meetings - Extra-ordinary Meeting",
    "Notice Of Shareholders Meetings - NCLT / Court Convened Meeting",
    "Notice Of Shareholders Meetings - Postal Ballot",
    "Other Restructuring",
    "Sale or disposal",
    "Slump Sale",
    "Acquisition",
    "NCLT / Court Convened Meeting",
    "Others",
    "Update-Acquisition / Scheme / Sale / Disposal / Reg30",
    "Change in Directors / Key Managerial Personnel / Auditor / Compliance Officer / Share Transfer Agent",
    "Corporate Insolvency Resolution Process",
    "Closure of Trading Window",
    "Loss of Share Certificate and Issue of Duplicate Share Certificate or Letter of Confirmation",
    "Impact of Audit Qualifications",
    "Reg. 32 (1), (3) - Statement of Deviation & Variation"
  ],
  "New Listing": ["New Listing"],
  "Result": [
    "Change in Accounting Year",
    "Financial Results",
    "Limited Review Report",
    "Auditors Report"
  ],
  "Corp. Action": [
    "Amalgamation / Merger / Demerger",
    "Bonus",
    "Book Closure",
    "Capital Reduction",
    "Dividend",
    "Record Date",
    "Sub-division / Stock Split",
    "Bonds / Right issue",
    "Consolidation of Shares"
  ]
}